name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Code Vulnerability scanning
        id: scan
        uses: anchore/scan-action@v3
        with:
          path: ${{ github.workspace }}
          fail-build: false
          severity-cutoff: high
          output-format: sarif

      - name: Upload vulnerability report (SARIF)
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ always() && steps.scan.outcome == 'success' }}
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Build, unit tests and integration tests
        run: |
          chmod +x gradlew
          ./gradlew build
